### ISSUE TITLE
Composer não funciona!

### ISSUE THREAD

**Issue by adrianoaspira** [nfephp-org/posprint#74]
Boa tarde,

estou tentando instalar via composer mas retorna o seguinte erro:
The "https://packagist.org/packages.json" file could not be downloaded: php_network_getaddresses: getaddrinfo failed: Name or service not known
failed to open stream: php_network_getaddresses: getaddrinfo failed: Name or service not known
https://packagist.org could not be fully loaded, package information was loaded from the local cache and may be out of date

[Composer\Downloader\TransportException]
  The "http://packagist.org/p/nfephp-org/posprint%246af4c56c4490ef32ce87584ea3cb8a8bec10834b06a783b4c94eabb8427cdca7.json" file could not be downloaded: php_network_
  getaddresses: getaddrinfo failed: Name or service not known
  failed to open stream: php_network_getaddresses: getaddrinfo failed: Name or service not known

**Comment by ninsky** [comment]
Same problem to me :( 

`composer require nfephp-org/posprint`

> [InvalidArgumentException]  
>   Could not find package nfephp-org/posprint at any version for your minimum-  
>   stability (stable)

**Comment by robmachado** [comment]
O pacote ainda está com "UNSTABLE" portanto você terá que forçar o uso de pacotes instáveis em SEU  composer.json, estabelecendo "minimum-stability": "dev"

The package is still "UNSTABLE" so you have to force the use of unstable packages on YOUR composer.json, establishing "minimum-stability", "dev"
