### ISSUE TITLE
Package endroid/qrcode is abandoned

### ISSUE THREAD

**Issue by mrcarromesa** [nfephp-org/posprint#82]
Bom dia, não sei se é do conhecimento do(s) desenvolvedor(es), porém ao realizar o require ou update no composer, desse projeto, obtenho o seguinte aviso: 

> Package endroid/qrcode is abandoned, you should avoid using it. Use endroid/qr-code instead. 

se isso já for de conhecimento, favor ignorar.

Obrigado.

**Comment by robmachado** [comment]
Sim
